import { SiteSettings, Product, Service, Project } from './types';

export const defaultSiteSettings: SiteSettings = {
  hero_title: 'TAMAN SAN JAYA - Taman Tropis Asri & Ruang Hijau Impian',
  hero_subtitle: 'Spesialis desain lanskap, pembuatan taman tropis, relief tebing alami, & tanaman hias berkualitas dengan garansi tumbuh 100%.',
  // Exact landscape garden image from Figma mockup
  hero_image_url: '/images/hero-garden.jpg',
  whatsapp_number: '6281234567890',
  whatsapp_message: 'Halo Taman San Jaya, saya ingin konsultasi mengenai jasa landscape taman & pemesanan tanaman.',
  address: 'Jl. Raya Hijau Asri No. 88, Workshop & Nursery Taman San Jaya',
  google_maps_url: 'https://maps.google.com',
  instagram_url: 'https://instagram.com/tamansanjaya',
  opening_hours: 'Senin - Minggu: 08.00 - 18.00 WIB',
};

export const defaultServices: Service[] = [
  {
    id: '1',
    title: 'Jasa Pembuatan',
    slug: 'jasa-pembuatan',
    short_desc: 'Pembuatan taman tropis modern, taman minimalis, relief tebing air terjun alami, stepping stone, hardscape, dan penanaman bergaransi tumbuh 100%.',
    full_desc: 'Eksekusi konstruksi lanskap menyeluruh dari olah lahan, instalasi drainase, pembuatan dinding batu andesit relief, penanaman rumput jepang, hingga penataan tanaman tropis dengan garansi tumbuh 100%.',
    icon_name: 'Hammer',
    features: [
      'Taman Tropis, Minimalis Modern & Zen Garden',
      'Relief Tebing Air Terjun & Air Mancur Alami',
      'Decking Kayu Ulin, Pergola, & Gazebo Santai',
      'Pemasangan Rumput & Sistem Drainase Alami',
      'Garansi Hidup & Tumbuh Tanaman 100%',
    ],
    image_url: '/images/Pembuatan.jpg',
    order_index: 1,
  },
  {
    id: '2',
    title: 'Jasa Perencanaan',
    slug: 'jasa-perencanaan',
    short_desc: 'Visualisasi desain konsep 2D & 3D realistis, survei pengukuran lahan, tata letak vegetasi adaptif, sistem drainase, dan rancangan anggaran biaya (RAB) transparan.',
    full_desc: 'Perencanaan matang dengan gambar kerja arsitektural 2D & render 3D fotorealistis. Menjamin penataan komposisi pohon, arah pencahayaan matahari, serta estimasi biaya yang presisi sebelum pembangunan dimulai.',
    icon_name: 'Compass',
    features: [
      'Visualisasi Konsep Desain 2D & 3D Realistis',
      'Survei Pengukuran Luas Lahan & Analisis Kontur Gratis',
      'Pemilihan Vegetasi Adaptif Iklim Tropis',
      'Rancangan Anggaran Biaya (RAB) Rinci & Transparan',
    ],
    image_url: '/images/Perencanaan.jpg',
    order_index: 2,
  },
  {
    id: '3',
    title: 'Jasa Perawatan',
    slug: 'jasa-perawatan',
    short_desc: 'Perawatan rutin berkala: pemangkasan dahan pohon, pemupukan nutrisi organik, penggemburan tanah, serta pengendalian hama & jamur berbasis Proteksi Tanaman IPB.',
    full_desc: 'Layanan pemeliharaan berkala agar taman Anda senantiasa asri, hijau, dan terbebas dari hama tanaman. Ditangani langsung dengan keilmuan patologi botani dari Fakultas Pertanian IPB University.',
    icon_name: 'Scissors',
    features: [
      'Pemangkasan Ranting & Pembentukan Tajuk Pohon',
      'Pemupukan Nutrisi Organik & Pupuk Daun Berkala',
      'Pengendalian Hama & Kutu Putih Berbasis Sains IPB',
      'Penggemburan Tanah & Pengisian Media Tanam Baru',
      'Paket Kunjungan Berkala Mingguan & Bulanan',
    ],
    image_url: '/images/Perawatan.jpg',
    order_index: 3,
  },
];

export const defaultProducts: Product[] = [
  {
    id: 'p1',
    name: 'Lidah Mertua (Sansevieria Trifasciata)',
    slug: 'lidah-mertua-sansevieria',
    category: 'Indoor & Outdoor',
    price: 75000,
    price_display: 'Rp 75.000',
    description: 'Tanaman hias tangguh penyerap racun udara dan polusi paling efektif. Sangat mudah dirawat dan cocok di sudut ruangan maupun pembatas teras.',
    care_instructions: 'Penyiraman 1x seminggu. Tahan di tempat minim cahaya hingga sinar matahari penuh.',
    image_url: '/images/lidah-mertua.jpg',
    in_stock: true,
    featured: true,
    order_index: 1,
    tokopedia_url: 'https://www.tokopedia.com/search?st=product&q=Lidah+Mertua+Sansevieria',
    shopee_url: 'https://shopee.co.id/search?keyword=Lidah+Mertua+Sansevieria',
  },
  {
    id: 'p2',
    name: 'Monstera Adansonii (Janda Bolong)',
    slug: 'monstera-janda-bolong',
    category: 'Indoor',
    price: 85000,
    price_display: 'Rp 85.000',
    description: 'Tanaman hias tropis merambat populer dengan lubang-lubang artistik alami pada helai daun. Sangat estetik untuk dekorasi meja, ambalan dinding, atau pot gantung.',
    care_instructions: 'Siram saat media tanam mulai mengering (2-3 hari sekali). Letakkan di area terang tanpa terkena sinar matahari langsung.',
    image_url: '/images/monstera-janda-bolong.jpg',
    in_stock: true,
    featured: true,
    order_index: 2,
    tokopedia_url: 'https://www.tokopedia.com/search?st=product&q=Monstera+Janda+Bolong',
    shopee_url: 'https://shopee.co.id/search?keyword=Monstera+Janda+Bolong',
  },
  {
    id: 'p3',
    name: 'Aglaonema (Sri Rejeki)',
    slug: 'aglaonema-sri-rejeki',
    category: 'Tanaman Daun',
    price: 125000,
    price_display: 'Rp 125.000',
    description: 'Ratu tanaman daun dengan corak hijau segar dan semburat artistik memikat. Dipercaya membawa keberuntungan, ketenangan, serta membersihkan udara dalam hunian.',
    care_instructions: 'Cahaya teduh terfilter, kelembapan seimbang, penyiraman teratur 2 kali seminggu pada media tanam poros.',
    image_url: '/images/aglaonema.jpg',
    in_stock: true,
    featured: true,
    order_index: 3,
    tokopedia_url: 'https://www.tokopedia.com/search?st=product&q=Aglaonema+Sri+Rejeki',
    shopee_url: 'https://shopee.co.id/search?keyword=Aglaonema+Sri+Rejeki',
  },
  {
    id: 'p4',
    name: 'Bunga Anggrek Bulan (Phalaenopsis)',
    slug: 'bunga-anggrek-bulan',
    category: 'Bunga & Koleksi',
    price: 145000,
    price_display: 'Rp 145.000',
    description: 'Pesona anggrek nusantara dengan kelopak bunga mekar anggun, elegan, dan tahan lama. Simbol keindahan abadi yang sangat cocok sebagai penghias ruang tamu utama.',
    care_instructions: 'Siram semprot halus 2 kali seminggu di akar/media pakis, sirkulasi udara lancar dan sinar pagi tidak langsung.',
    image_url: '/images/anggrek.jpg',
    in_stock: true,
    featured: true,
    order_index: 4,
    tokopedia_url: 'https://www.tokopedia.com/search?st=product&q=Bunga+Anggrek+Bulan',
    shopee_url: 'https://shopee.co.id/search?keyword=Bunga+Anggrek+Bulan',
  },
];

export const defaultProjects: Project[] = [
  {
    id: 'proj1',
    title: 'Taman Minimalis Modern & Rumput Hijau Rapat',
    category: 'Taman Minimalis',
    location: 'Hunian Residensial Mewah',
    image_url: '/images/proyek-4.avif',
    gallery_images: ['/images/proyek-4.avif', '/images/proyek-2.jpg', '/images/proyek-1.jpeg', '/images/Pembuatan.jpg'],
    description: 'Penataan tanaman bonsai peneduh artistik, batuan koral hias, hamparan rumput jepang rapi, dan vegetasi tropis pembatas pagar hunian privat.',
    order_index: 1,
  },
  {
    id: 'proj2',
    title: 'Taman Tropis Alami & Jalan Setapak Villa',
    category: 'Taman Tropis',
    location: 'Kawasan Villa & Hunian Tropis',
    image_url: '/images/proyek-2.jpg',
    gallery_images: ['/images/proyek-2.jpg', '/images/proyek-4.avif', '/images/proyek-3.jpg', '/images/Perawatan.jpg'],
    description: 'Kombinasi pohon kamboja berbunga harum, palem tropis, tanaman puring hias, dan pedestrian paving yang asri serta rindang.',
    order_index: 2,
  },
  {
    id: 'proj3',
    title: 'Perencanaan Desain Lanskap 3D Kawasan & Taman Terbuka',
    category: 'Perencanaan 3D',
    location: 'Masterplan Kawasan Publik & Privat',
    image_url: '/images/proyek-1.jpeg',
    gallery_images: ['/images/proyek-1.jpeg', '/images/Perencanaan.jpg', '/images/proyek-4.avif', '/images/proyek-2.jpg'],
    description: 'Rancangan arsitektural 3D fotorealistis meliputi jalur pejalan kaki, gazebo santai, area hijau terbuka, serta penataan komposisi vegetasi terstruktur.',
    order_index: 3,
  },
  {
    id: 'proj4',
    title: 'Taman Air Mancur Relief Batu Alam & Gazebo Bersantai',
    category: 'Relief Tebing & Air',
    location: 'Courtyard Hunian Tropis',
    image_url: '/images/proyek-3.jpg',
    gallery_images: ['/images/proyek-3.jpg', '/images/proyek-2.jpg', '/images/Pembuatan.jpg', '/images/proyek-4.avif'],
    description: 'Ornamen air mancur bertingkat relief batu alam berpadu dengan gazebo kayu tradisional dan pepohonan tropis yang menyejukkan.',
    order_index: 4,
  },
  {
    id: 'proj5',
    title: 'Konstruksi & Eksekusi Pembuatan Lanskap Riil',
    category: 'Pengerjaan Lanskap',
    location: 'Area Hunian & Komersial',
    image_url: '/images/Pembuatan.jpg',
    gallery_images: ['/images/Pembuatan.jpg', '/images/proyek-1.jpeg', '/images/proyek-3.jpg', '/images/Perawatan.jpg'],
    description: 'Eksekusi fisik pengerjaan lanskap dari olah lahan, seleksi bibit unggul, pemupukan organik, hingga penataan hardscape bergaransi tumbuh 100%.',
    order_index: 5,
  },
];
