import { SiteSettings, Product, Service, Project } from './types';

export const defaultSiteSettings: SiteSettings = {
  hero_title: 'TAMAN SAN JAYA - Taman Tropis Asri & Ruang Hijau Impian',
  hero_subtitle: 'Spesialis desain lanskap, pembuatan taman tropis, relief tebing alami, & tanaman hias berkualitas dengan garansi tumbuh 100%.',
  // Exact landscape garden image from Figma mockup
  hero_image_url: '/images/hero-garden.jpg',
  whatsapp_number: '6281234567890',
  whatsapp_message: 'Halo Taman San Jaya, saya ingin konsultasi mengenai jasa landscape taman & pemesanan tanaman.',
  address: 'Jl. Raya Hijau Asri No. 88, Workshop & Nursery Taman San Jaya',
  google_maps_url: 'https://maps.google.com',
  instagram_url: 'https://instagram.com/tamansanjaya',
  opening_hours: 'Senin - Minggu: 08.00 - 18.00 WIB',
};

export const defaultServices: Service[] = [
  {
    id: '1',
    title: 'Jasa Pembuatan',
    slug: 'jasa-pembuatan',
    short_desc: 'Pembuatan taman tropis modern, taman minimalis, relief tebing air terjun alami, stepping stone, hardscape, dan penanaman bergaransi tumbuh 100%.',
    full_desc: 'Eksekusi konstruksi lanskap menyeluruh dari olah lahan, instalasi drainase, pembuatan dinding batu andesit relief, penanaman rumput jepang, hingga penataan tanaman tropis dengan garansi tumbuh 100%.',
    icon_name: 'Hammer',
    features: [
      'Taman Tropis, Minimalis Modern & Zen Garden',
      'Relief Tebing Air Terjun & Air Mancur Alami',
      'Decking Kayu Ulin, Pergola, & Gazebo Santai',
      'Pemasangan Rumput & Sistem Drainase Alami',
      'Garansi Hidup & Tumbuh Tanaman 100%',
    ],
    image_url: '/images/Pembuatan.jpg',
    order_index: 1,
  },
  {
    id: '2',
    title: 'Jasa Perencanaan',
    slug: 'jasa-perencanaan',
    short_desc: 'Visualisasi desain konsep 2D & 3D realistis, survei pengukuran lahan, tata letak vegetasi adaptif, sistem drainase, dan rancangan anggaran biaya (RAB) transparan.',
    full_desc: 'Perencanaan matang dengan gambar kerja arsitektural 2D & render 3D fotorealistis. Menjamin penataan komposisi pohon, arah pencahayaan matahari, serta estimasi biaya yang presisi sebelum pembangunan dimulai.',
    icon_name: 'Compass',
    features: [
      'Visualisasi Konsep Desain 2D & 3D Realistis',
      'Survei Pengukuran Luas Lahan & Analisis Kontur Gratis',
      'Pemilihan Vegetasi Adaptif Iklim Tropis',
      'Rancangan Anggaran Biaya (RAB) Rinci & Transparan',
    ],
    image_url: '/images/Perencanaan.jpg',
    order_index: 2,
  },
  {
    id: '3',
    title: 'Jasa Perawatan',
    slug: 'jasa-perawatan',
    short_desc: 'Perawatan rutin berkala: pemangkasan dahan pohon, pemupukan nutrisi organik, penggemburan tanah, serta pengendalian hama & jamur berbasis Proteksi Tanaman IPB.',
    full_desc: 'Layanan pemeliharaan berkala agar taman Anda senantiasa asri, hijau, dan terbebas dari hama tanaman. Ditangani langsung dengan keilmuan patologi botani dari Fakultas Pertanian IPB University.',
    icon_name: 'Scissors',
    features: [
      'Pemangkasan Ranting & Pembentukan Tajuk Pohon',
      'Pemupukan Nutrisi Organik & Pupuk Daun Berkala',
      'Pengendalian Hama & Kutu Putih Berbasis Sains IPB',
      'Penggemburan Tanah & Pengisian Media Tanam Baru',
      'Paket Kunjungan Berkala Mingguan & Bulanan',
    ],
    image_url: '/images/Perawatan.jpg',
    order_index: 3,
  },
];

export const defaultProducts: Product[] = [
  {
    id: 'p1',
    name: 'Lidah Mertua (Sansevieria Trifasciata)',
    slug: 'lidah-mertua-sansevieria',
    category: 'Indoor & Outdoor',
    price: 75000,
    price_display: 'Rp 75.000',
    description: 'Tanaman hias tangguh penyerap racun udara dan polusi paling efektif. Sangat mudah dirawat dan cocok di sudut ruangan maupun pembatas teras.',
    care_instructions: 'Penyiraman 1x seminggu. Tahan di tempat minim cahaya hingga sinar matahari penuh.',
    image_url: 'https://images.unsplash.com/photo-1593691509543-c55fb32e7355?auto=format&fit=crop&w=800&q=80',
    in_stock: true,
    featured: true,
    order_index: 1,
  },
  {
    id: 'p2',
    name: 'Monstera Deliciosa (King Monstera)',
    slug: 'monstera-deliciosa',
    category: 'Indoor',
    price: 165000,
    price_display: 'Rp 165.000',
    description: 'Tanaman primadona dengan daun besar berbelah estetik. Memberikan kesan tropis modern yang mewah di dalam ruangan atau semi-outdoor.',
    care_instructions: 'Siram saat media tanam mulai kering. Letakkan di tempat terang tidak terkena matahari langsung.',
    image_url: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&w=800&q=80',
    in_stock: true,
    featured: true,
    order_index: 2,
  },
  {
    id: 'p3',
    name: 'Pohon Palem Merah (Cyrtostachys Renda)',
    slug: 'palem-merah',
    category: 'Pohon & Palem',
    price: 350000,
    price_display: 'Mulai Rp 350.000',
    description: 'Palem eksotis dengan pelepah merah cerah yang sangat berkelas. Sangat ideal untuk pintu gerbang hunian atau focal point di taman utama.',
    care_instructions: 'Suka sinar matahari langsung dan kelembapan air yang teratur setiap hari.',
    image_url: 'https://images.unsplash.com/photo-1512428813834-c702c7702b78?auto=format&fit=crop&w=800&q=80',
    in_stock: true,
    featured: true,
    order_index: 3,
  },
  {
    id: 'p4',
    name: 'Aglaonema Suksom Jaipong Merah',
    slug: 'aglaonema-suksom-jaipong',
    category: 'Tanaman Daun',
    price: 125000,
    price_display: 'Rp 125.000',
    description: 'Varian ratu daun dengan warna merah menyala spektakuler. Dipercaya sebagai simbol keberuntungan dan penambah kesegaran ruang tamu.',
    care_instructions: 'Tempatkan di tempat teduh bersirkulasi udara baik. Hindari sinar matahari terik.',
    image_url: 'https://images.unsplash.com/photo-1617173944883-6ffbd35d584d?auto=format&fit=crop&w=800&q=80',
    in_stock: true,
    featured: true,
    order_index: 4,
  },
  {
    id: 'p5',
    name: 'Bonsai Beringin Dolar (Ficus Compacta)',
    slug: 'bonsai-beringin-dolar',
    category: 'Bonsai & Koleksi',
    price: 850000,
    price_display: 'Rp 850.000',
    description: 'Bonsai bernilai seni tinggi dengan batang kokoh meliuk artistik dan daun bundar tebal mengkilap. Sangat anggun di beranda atau taman depan.',
    care_instructions: 'Letakkan di area terbuka berlimpah sinar matahari. Pangkas ranting secara teratur.',
    image_url: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=800&q=80',
    in_stock: true,
    featured: false,
    order_index: 5,
  },
  {
    id: 'p6',
    name: 'Philodendron Birkin Zebra',
    slug: 'philodendron-birkin',
    category: 'Indoor',
    price: 95000,
    price_display: 'Rp 95.000',
    description: 'Tanaman indoor dengan guratan garis krem-putih yang sangat kontras di atas daun hijau tua mengkilap. Kompak dan memesona di pot meja.',
    care_instructions: 'Siram 2 kali seminggu, media tanam berporositas baik.',
    image_url: 'https://images.unsplash.com/photo-1598880940371-c756e015fea1?auto=format&fit=crop&w=800&q=80',
    in_stock: true,
    featured: false,
    order_index: 6,
  },
  {
    id: 'p7',
    name: 'Calathea Orbifolia Hijau Lebar',
    slug: 'calathea-orbifolia',
    category: 'Tanaman Daun',
    price: 110000,
    price_display: 'Rp 110.000',
    description: 'Calathea berdaun lebar melingkar dengan pola garis perak metalik yang sangat tenang dan menenangkan pandangan mata.',
    care_instructions: 'Suka kelembapan tinggi, hindari air dengan kadar kaporit tinggi.',
    image_url: 'https://images.unsplash.com/photo-1620127682256-0f562916b9d6?auto=format&fit=crop&w=800&q=80',
    in_stock: true,
    featured: false,
    order_index: 7,
  },
  {
    id: 'p8',
    name: 'Pohon Ketapang Kencana Variegata',
    slug: 'ketapang-kencana-variegata',
    category: 'Pohon & Palem',
    price: 550000,
    price_display: 'Mulai Rp 550.000',
    description: 'Pohon peneduh berkanopi bertingkat (pagoda) dengan kombinasi daun hijau dan putih variegata yang sangat mewah untuk halaman rumah.',
    care_instructions: 'Tanam di tanah luas terbuka yang terkena sinar matahari penuh sepanjang hari.',
    image_url: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80',
    in_stock: true,
    featured: false,
    order_index: 8,
  },
];

export const defaultProjects: Project[] = [
  {
    id: 'proj1',
    title: 'Taman Minimalis Modern & Rumput Hijau Rapat',
    category: 'Taman Minimalis',
    location: 'Hunian Residensial Mewah',
    image_url: '/images/proyek-4.avif',
    description: 'Penataan tanaman bonsai peneduh artistik, batuan koral hias, hamparan rumput jepang rapi, dan vegetasi tropis pembatas pagar hunian privat.',
    order_index: 1,
  },
  {
    id: 'proj2',
    title: 'Taman Tropis Alami & Jalan Setapak Villa',
    category: 'Taman Tropis',
    location: 'Kawasan Villa & Hunian Tropis',
    image_url: '/images/proyek-2.jpg',
    description: 'Kombinasi pohon kamboja berbunga harum, palem tropis, tanaman puring hias, dan pedestrian paving yang asri serta rindang.',
    order_index: 2,
  },
  {
    id: 'proj3',
    title: 'Perencanaan Desain Lanskap 3D Kawasan & Taman Terbuka',
    category: 'Perencanaan 3D',
    location: 'Masterplan Kawasan Publik & Privat',
    image_url: '/images/proyek-1.jpeg',
    description: 'Rancangan arsitektural 3D fotorealistis meliputi jalur pejalan kaki, gazebo santai, area hijau terbuka, serta penataan komposisi vegetasi terstruktur.',
    order_index: 3,
  },
  {
    id: 'proj4',
    title: 'Taman Air Mancur Relief Batu Alam & Gazebo Bersantai',
    category: 'Relief Tebing & Air',
    location: 'Courtyard Hunian Tropis',
    image_url: '/images/proyek-3.jpg',
    description: 'Ornamen air mancur bertingkat relief batu alam berpadu dengan gazebo kayu tradisional dan pepohonan tropis yang menyejukkan.',
    order_index: 4,
  },
  {
    id: 'proj5',
    title: 'Konstruksi & Eksekusi Pembuatan Lanskap Riil',
    category: 'Pengerjaan Lanskap',
    location: 'Area Hunian & Komersial',
    image_url: '/images/Pembuatan.jpg',
    description: 'Eksekusi fisik pengerjaan lanskap dari olah lahan, seleksi bibit unggul, pemupukan organik, hingga penataan hardscape bergaransi tumbuh 100%.',
    order_index: 5,
  },
];
