import { SiteSettings, Product, Service, Project } from './types';

export const defaultSiteSettings: SiteSettings = {
  hero_title: 'Wujudkan Taman Tropis Asri & Bernilai Estetika Tinggi',
  hero_subtitle: 'Spesialis landscape architecture, pengerjaan taman hunian & komersial, kolam ikan koi dengan filtrasi modern, relief tebing alami, serta penyediaan tanaman hias berkualitas.',
  // Exact landscape garden image from Figma mockup
  hero_image_url: '/images/hero-garden.jpg',
  whatsapp_number: '6281234567890',
  whatsapp_message: 'Halo Taman San Jaya, saya ingin konsultasi mengenai jasa landscape taman & pemesanan tanaman.',
  address: 'Jl. Raya Hijau Asri No. 88, Workshop & Nursery Taman San Jaya',
  google_maps_url: 'https://maps.google.com',
  instagram_url: 'https://instagram.com/tamansanjaya',
  opening_hours: 'Senin - Minggu: 08.00 - 18.00 WIB',
};

export const defaultServices: Service[] = [
  {
    id: '1',
    title: 'Jasa Perencanaan & Desain Taman',
    slug: 'jasa-perencanaan',
    short_desc: 'Visualisasi desain taman 2D & 3D photorealistic yang presisi, dirancang khusus menyesuaikan karakter arsitektur dan lahan Anda.',
    full_desc: 'Perencanaan matang adalah kunci taman yang indah dan tahan lama. Kami menyusun tata letak vegetasi, sistem drainase, instalasi pencahayaan taman (garden lighting), serta pemilihan material hardscape sebelum proses pengerjaan dimulai.',
    icon_name: 'Compass',
    features: [
      'Konsep Desain 2D & 3D Realistis',
      'Pemilihan Jenis Tanaman Sesuai Iklim & Arah Cahaya',
      'Rancangan Anggaran Biaya (RAB) Terperinci & Transparan',
      'Survei Lokasi & Pengukuran Luas Lahan Gratis',
    ],
    image_url: 'https://images.unsplash.com/photo-1598902108854-10e335adac99?auto=format&fit=crop&w=800&q=80',
    order_index: 1,
  },
  {
    id: '2',
    title: 'Jasa Pembuatan Taman & Kolam',
    slug: 'jasa-pembuatan',
    short_desc: 'Eksekusi pengerjaan taman dari nol hingga jadi: taman tropis, minimalis modern, kolam ikan koi, relief tebing, dan vertical garden.',
    full_desc: 'Ditangani langsung oleh tim tukang taman berpengalaman puluhan tahun dengan teknik penanaman dan olah tanah yang tepat. Setiap pengerjaan kami lengkapi dengan garansi hidup tanaman untuk menjamin kepuasan Anda.',
    icon_name: 'Hammer',
    features: [
      'Pengerjaan Hardscape (Jalan Setapak, Decking, Dinding Batu)',
      'Kolam Ikan Koi dengan Sistem Filtrasi Modern 4 Chamber',
      'Relief Tebing Air Terjun Alami & Ornamen Artistik',
      'Pemasangan Rumput Gajah Mini, Jepang, atau Golf',
      'Garansi Tumbuh & Hidup Tanaman',
    ],
    image_url: 'https://images.unsplash.com/photo-1558904541-efa8c4a5c963?auto=format&fit=crop&w=800&q=80',
    order_index: 2,
  },
  {
    id: '3',
    title: 'Jasa Perawatan & Pemeliharaan Taman',
    slug: 'jasa-perawatan',
    short_desc: 'Layanan perawatan berkala agar taman Anda selalu segar, rapi, dan bebas hama sepanjang tahun.',
    full_desc: 'Taman yang indah membutuhkan sentuhan perawatan profesional. Kami melayani kunjungan rutin untuk pemangkasan dahan pohon, pemupukan nutrisi organik, pembersihan gulma, serta penyemprotan anti hama.',
    icon_name: 'Scissors',
    features: [
      'Pemangkasan Ranting, Daun Kering & Pembentukan Tajuk',
      'Pemupukan Berkala (Pupuk Organik & Pupuk Daun)',
      'Pengendalian Hama, Kutu Putih & Jamur Tanaman',
      'Penggemburan Tanah & Pengisian Ulang Media Tanam',
      'Tersedia Paket Kunjungan Mingguan & Bulanan',
    ],
    image_url: 'https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=800&q=80',
    order_index: 3,
  },
];

export const defaultProducts: Product[] = [
  {
    id: 'p1',
    name: 'Lidah Mertua (Sansevieria Trifasciata)',
    slug: 'lidah-mertua-sansevieria',
    category: 'Indoor & Outdoor',
    price: 75000,
    price_display: 'Rp 75.000',
    description: 'Tanaman hias tangguh penyerap racun udara dan polusi paling efektif. Sangat mudah dirawat dan cocok di sudut ruangan maupun pembatas teras.',
    care_instructions: 'Penyiraman 1x seminggu. Tahan di tempat minim cahaya hingga sinar matahari penuh.',
    image_url: 'https://images.unsplash.com/photo-1593691509543-c55fb32e7355?auto=format&fit=crop&w=800&q=80',
    in_stock: true,
    featured: true,
    order_index: 1,
  },
  {
    id: 'p2',
    name: 'Monstera Deliciosa (King Monstera)',
    slug: 'monstera-deliciosa',
    category: 'Indoor',
    price: 165000,
    price_display: 'Rp 165.000',
    description: 'Tanaman primadona dengan daun besar berbelah estetik. Memberikan kesan tropis modern yang mewah di dalam ruangan atau semi-outdoor.',
    care_instructions: 'Siram saat media tanam mulai kering. Letakkan di tempat terang tidak terkena matahari langsung.',
    image_url: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&w=800&q=80',
    in_stock: true,
    featured: true,
    order_index: 2,
  },
  {
    id: 'p3',
    name: 'Pohon Palem Merah (Cyrtostachys Renda)',
    slug: 'palem-merah',
    category: 'Pohon & Palem',
    price: 350000,
    price_display: 'Mulai Rp 350.000',
    description: 'Palem eksotis dengan pelepah merah cerah yang sangat berkelas. Sangat ideal untuk pintu gerbang hunian atau focal point di taman utama.',
    care_instructions: 'Suka sinar matahari langsung dan kelembapan air yang teratur setiap hari.',
    image_url: 'https://images.unsplash.com/photo-1512428813834-c702c7702b78?auto=format&fit=crop&w=800&q=80',
    in_stock: true,
    featured: true,
    order_index: 3,
  },
  {
    id: 'p4',
    name: 'Aglaonema Suksom Jaipong Merah',
    slug: 'aglaonema-suksom-jaipong',
    category: 'Tanaman Daun',
    price: 125000,
    price_display: 'Rp 125.000',
    description: 'Varian ratu daun dengan warna merah menyala spektakuler. Dipercaya sebagai simbol keberuntungan dan penambah kesegaran ruang tamu.',
    care_instructions: 'Tempatkan di tempat teduh bersirkulasi udara baik. Hindari sinar matahari terik.',
    image_url: 'https://images.unsplash.com/photo-1617173944883-6ffbd35d584d?auto=format&fit=crop&w=800&q=80',
    in_stock: true,
    featured: true,
    order_index: 4,
  },
  {
    id: 'p5',
    name: 'Bonsai Beringin Dolar (Ficus Compacta)',
    slug: 'bonsai-beringin-dolar',
    category: 'Bonsai & Koleksi',
    price: 850000,
    price_display: 'Rp 850.000',
    description: 'Bonsai bernilai seni tinggi dengan batang kokoh meliuk artistik dan daun bundar tebal mengkilap. Sangat anggun di beranda atau taman depan.',
    care_instructions: 'Letakkan di area terbuka berlimpah sinar matahari. Pangkas ranting secara teratur.',
    image_url: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=800&q=80',
    in_stock: true,
    featured: false,
    order_index: 5,
  },
  {
    id: 'p6',
    name: 'Philodendron Birkin Zebra',
    slug: 'philodendron-birkin',
    category: 'Indoor',
    price: 95000,
    price_display: 'Rp 95.000',
    description: 'Tanaman indoor dengan guratan garis krem-putih yang sangat kontras di atas daun hijau tua mengkilap. Kompak dan memesona di pot meja.',
    care_instructions: 'Siram 2 kali seminggu, media tanam berporositas baik.',
    image_url: 'https://images.unsplash.com/photo-1598880940371-c756e015fea1?auto=format&fit=crop&w=800&q=80',
    in_stock: true,
    featured: false,
    order_index: 6,
  },
  {
    id: 'p7',
    name: 'Calathea Orbifolia Hijau Lebar',
    slug: 'calathea-orbifolia',
    category: 'Tanaman Daun',
    price: 110000,
    price_display: 'Rp 110.000',
    description: 'Calathea berdaun lebar melingkar dengan pola garis perak metalik yang sangat tenang dan menenangkan pandangan mata.',
    care_instructions: 'Suka kelembapan tinggi, hindari air dengan kadar kaporit tinggi.',
    image_url: 'https://images.unsplash.com/photo-1620127682256-0f562916b9d6?auto=format&fit=crop&w=800&q=80',
    in_stock: true,
    featured: false,
    order_index: 7,
  },
  {
    id: 'p8',
    name: 'Pohon Ketapang Kencana Variegata',
    slug: 'ketapang-kencana-variegata',
    category: 'Pohon & Palem',
    price: 550000,
    price_display: 'Mulai Rp 550.000',
    description: 'Pohon peneduh berkanopi bertingkat (pagoda) dengan kombinasi daun hijau dan putih variegata yang sangat mewah untuk halaman rumah.',
    care_instructions: 'Tanam di tanah luas terbuka yang terkena sinar matahari penuh sepanjang hari.',
    image_url: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80',
    in_stock: true,
    featured: false,
    order_index: 8,
  },
];

export const defaultProjects: Project[] = [
  {
    id: 'proj1',
    title: 'Taman Tropis Modern & Gazebo Santai',
    category: 'Taman Tropis',
    location: 'Hunian Residensial Jakarta Selatan',
    image_url: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=1200&q=80',
    description: 'Perpaduan rumput jepang rapat, tanaman kamboja fosil, tanaman pakis, serta stepping stone alam yang menyatu dengan decking kayu teras.',
    order_index: 1,
  },
  {
    id: 'proj2',
    title: 'Kolam Ikan Koi Minimalis & Dinding Batu Alam Andesit',
    category: 'Kolam Koi',
    location: 'BSD City, Tangerang Selatan',
    image_url: 'https://images.unsplash.com/photo-1584467541268-b040f83be3fd?auto=format&fit=crop&w=1200&q=80',
    description: 'Instalasi kolam koi berfiltrasi modern 4 chamber dengan gemericik air terjun mini dinding relief andesit hitam dan pencahayaan underwater.',
    order_index: 2,
  },
  {
    id: 'proj3',
    title: 'Taman Kering Zen Garden Konsep Jepang',
    category: 'Taman Kering (Zen)',
    location: 'Menteng, Jakarta Pusat',
    image_url: 'https://images.unsplash.com/photo-1558904541-efa8c4a5c963?auto=format&fit=crop&w=1200&q=80',
    description: 'Konsep taman minimalis low-maintenance dengan kombinasi batu koral putih, tanaman sikas, bambu hias, dan lentera batu khas Jepang.',
    order_index: 3,
  },
  {
    id: 'proj4',
    title: 'Vertical Garden Dinding Hijau Tropis',
    category: 'Vertical Garden',
    location: 'Commercial Cafe & Bistro, Senopati',
    image_url: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=1200&q=80',
    description: 'Dinding hidup seluas 24m² dengan sistem irigasi otomatis (drip system) berisikan aneka varietas pakis sarang burung, tanduk rusa, dan philodendron.',
    order_index: 4,
  },
];
